[package]
name = "rolling-dice"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
clap = { version = "4.1", features = ["derive"] }
regex = "1.5.4"
csv = "1.3.1"
dirs = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
chrono = "0.4.42"
